"""Google Gmail provider constants."""

GOOGLE_GMAIL_BASE_URL = "https://gmail.googleapis.com/gmail/v1"
GOOGLE_GMAIL_MESSAGES_ENDPOINT = f"{GOOGLE_GMAIL_BASE_URL}/users/me/messages"
GOOGLE_GMAIL_DRAFTS_ENDPOINT = f"{GOOGLE_GMAIL_BASE_URL}/users/me/drafts"
GOOGLE_GMAIL_PROFILE_ENDPOINT = f"{GOOGLE_GMAIL_BASE_URL}/users/me/profile"

GOOGLE_GMAIL_SYSTEM_LABEL_INBOX = "INBOX"
GOOGLE_GMAIL_SYSTEM_LABEL_UNREAD = "UNREAD"
GOOGLE_GMAIL_SYSTEM_LABEL_STARRED = "STARRED"
GOOGLE_GMAIL_SYSTEM_LABEL_SPAM = "SPAM"
GOOGLE_GMAIL_SYSTEM_LABEL_TRASH = "TRASH"

HTTP_TIMEOUT_SECONDS = 25.0
MAX_PAGE_SIZE = 500
