import { StyleSheet, Dimensions, Platform } from 'react-native';
import { colors } from '@beeapp/design-system';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
export const PANEL_WIDTH = Math.min(SCREEN_WIDTH * 0.84, 340);

export const sideMenuStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: 'rgba(26, 26, 46, 0.45)',
  },
  backdrop: {
    flex: 1,
  },
  panel: {
    width: PANEL_WIDTH,
    backgroundColor: colors.neutral.gray50,
    paddingTop: Platform.OS === 'ios' ? 56 : 32,
  },
  panelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.neutral.gray200,
    backgroundColor: colors.neutral.gray50,
  },
  panelTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.neutral.text,
  },
  closeBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: colors.neutral.white,
    borderWidth: 1,
    borderColor: colors.neutral.gray200,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileCard: {
    backgroundColor: colors.neutral.white,
    borderRadius: 24,
    paddingVertical: 20,
    paddingHorizontal: 16,
    marginHorizontal: 16,
    marginTop: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.neutral.gray200,
  },
  avatarWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#F3E8FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    borderWidth: 2,
    borderColor: '#DDD6FE',
  },
  avatarText: {
    fontSize: 28,
    fontWeight: '800',
    color: colors.brand.primary,
  },
  onlineBadge: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    width: 13,
    height: 13,
    borderRadius: 7,
    backgroundColor: colors.semantic.success,
    borderWidth: 2.5,
    borderColor: colors.neutral.white,
  },
  profileName: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.neutral.text,
    marginBottom: 3,
  },
  profileOccupation: {
    fontSize: 12,
    color: colors.neutral.gray600,
    fontWeight: '600',
    marginBottom: 8,
  },
  companyBadgeRow: {
    backgroundColor: colors.neutral.gray50,
    borderRadius: 12,
    paddingVertical: 5,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: colors.neutral.gray200,
    marginBottom: 14,
  },
  companyNameText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.neutral.text,
    textAlign: 'center',
  },
  editProfileBtn: {
    backgroundColor: colors.neutral.gray100,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 20,
  },
  editProfileBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.neutral.text,
  },
  groupHeader: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.neutral.gray600,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginHorizontal: 20,
    marginTop: 18,
    marginBottom: 8,
  },
  optionsCard: {
    backgroundColor: colors.neutral.white,
    borderRadius: 20,
    marginHorizontal: 16,
    borderWidth: 1,
    borderColor: colors.neutral.gray200,
    overflow: 'hidden',
  },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.neutral.gray100,
  },
  optionIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  optionLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.neutral.text,
    flex: 1,
  },
  switchOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  switchTextCol: {
    flex: 1,
    paddingRight: 8,
  },
  switchDesc: {
    fontSize: 10,
    color: colors.neutral.gray600,
    marginTop: 2,
    lineHeight: 14,
    fontWeight: '500',
  },
  signOutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FEE2E2',
    borderWidth: 1,
    borderColor: '#FEE2E2',
    borderRadius: 16,
    paddingVertical: 14,
    marginHorizontal: 16,
    marginTop: 24,
    marginBottom: 14,
  },
  signOutBtnText: {
    color: colors.semantic.error,
    fontSize: 14,
    fontWeight: '700',
  },
  versionText: {
    fontSize: 11,
    color: colors.neutral.gray500,
    textAlign: 'center',
    fontWeight: '500',
  },
});
