from django.urls import path

from apps.chat.views import (
    ChatBootstrapView,
    ChatConversationAttachmentUploadView,
    ChatConversationClearView,
    ChatConversationDetailView,
    ChatConversationMessagesView,
    ChatConversationParticipantsView,
    ChatConversationReadView,
    ChatDirectConversationsView,
    ChatGroupConversationInvitesView,
    ChatGroupInviteDetailView,
    ChatGroupInviteResponseView,
    ChatGroupInvitesView,
    ChatGroupLeaveView,
    ChatGroupParticipantDetailView,
    ChatGroupsView,
    ChatIdentitiesView,
    ChatInboxView,
    ChatMessageAttachmentAccessView,
    ChatMessageAttachmentView,
    ChatMessageDetailView,
    ChatMessageReadersView,
    ChatMessageReactionDetailView,
    ChatMessageReactionsView,
    ChatMessageReadStatusView,
)


urlpatterns = [
    path(
        "bootstrap/",
        ChatBootstrapView.as_view(),
        name="chat-bootstrap",
    ),
    path(
        "identities/",
        ChatIdentitiesView.as_view(),
        name="chat-identities",
    ),
    path(
        "inbox/",
        ChatInboxView.as_view(),
        name="chat-inbox",
    ),
    path(
        "direct-conversations/",
        ChatDirectConversationsView.as_view(),
        name="chat-direct-conversations",
    ),
    path(
        "conversations/<uuid:conversation_id>/",
        ChatConversationDetailView.as_view(),
        name="chat-conversation-detail",
    ),
    path(
        "conversations/<uuid:conversation_id>/clear/",
        ChatConversationClearView.as_view(),
        name="chat-conversation-clear",
    ),
    path(
        "conversations/<uuid:conversation_id>/participants/",
        ChatConversationParticipantsView.as_view(),
        name="chat-conversation-participants",
    ),
    path(
        "conversations/<uuid:conversation_id>/messages/",
        ChatConversationMessagesView.as_view(),
        name="chat-conversation-messages",
    ),
    path(
        "conversations/<uuid:conversation_id>/attachments/",
        ChatConversationAttachmentUploadView.as_view(),
        name="chat-conversation-attachment-upload",
    ),
    path(
        "conversations/<uuid:conversation_id>/read/",
        ChatConversationReadView.as_view(),
        name="chat-conversation-read",
    ),
    path(
        "groups/",
        ChatGroupsView.as_view(),
        name="chat-groups",
    ),
    path(
        "groups/<uuid:conversation_id>/invites/",
        ChatGroupConversationInvitesView.as_view(),
        name="chat-group-invites-create",
    ),
    path(
        "groups/<uuid:conversation_id>/leave/",
        ChatGroupLeaveView.as_view(),
        name="chat-group-leave",
    ),
    path(
        (
            "groups/<uuid:conversation_id>/participants/"
            "<uuid:identity_id>/"
        ),
        ChatGroupParticipantDetailView.as_view(),
        name="chat-group-participant-detail",
    ),
    path(
        "group-invites/",
        ChatGroupInvitesView.as_view(),
        name="chat-group-invites",
    ),
    path(
        "group-invites/<uuid:invite_id>/",
        ChatGroupInviteDetailView.as_view(),
        name="chat-group-invite-detail",
    ),
    path(
        "group-invites/<uuid:invite_id>/response/",
        ChatGroupInviteResponseView.as_view(),
        name="chat-group-invite-response",
    ),
    path(
        "messages/<uuid:message_id>/",
        ChatMessageDetailView.as_view(),
        name="chat-message-detail",
    ),
    path(
        "messages/<uuid:message_id>/attachment/",
        ChatMessageAttachmentView.as_view(),
        name="chat-message-attachment",
    ),
    path(
        "messages/<uuid:message_id>/attachment/access/",
        ChatMessageAttachmentAccessView.as_view(),
        name="chat-message-attachment-access",
    ),
    path(
        "messages/<uuid:message_id>/read-status/",
        ChatMessageReadStatusView.as_view(),
        name="chat-message-read-status",
    ),
    path(
        "messages/<uuid:message_id>/readers/",
        ChatMessageReadersView.as_view(),
        name="chat-message-readers",
    ),
    path(
        "messages/<uuid:message_id>/reactions/",
        ChatMessageReactionsView.as_view(),
        name="chat-message-reactions",
    ),
    path(
        "messages/<uuid:message_id>/reactions/<str:emoji>/",
        ChatMessageReactionDetailView.as_view(),
        name="chat-message-reaction-detail",
    ),
]