from django.urls import path

from apps.mail.views import (
    MailDraftDetailView,
    MailDraftSendView,
    MailDraftsView,
    MailIntegrationDetailView,
    MailIntegrationsView,
    MailMessageActionView,
    MailMessageAttachmentDownloadView,
    MailMessageDetailView,
    MailMessageMoveView,
    MailMessagesView,
    MailMessageStateView,
    MailSyncView,
)


urlpatterns = [
    path(
        "integrations/",
        MailIntegrationsView.as_view(),
        name="mail-integrations",
    ),
    path(
        "integrations/<uuid:integration_id>/",
        MailIntegrationDetailView.as_view(),
        name="mail-integration-detail",
    ),
    path(
        "messages/",
        MailMessagesView.as_view(),
        name="mail-messages",
    ),
    path(
        "messages/<uuid:message_id>/",
        MailMessageDetailView.as_view(),
        name="mail-message-detail",
    ),
    path(
        "messages/<uuid:message_id>/state/",
        MailMessageStateView.as_view(),
        name="mail-message-state",
    ),
    path(
        "messages/<uuid:message_id>/move/",
        MailMessageMoveView.as_view(),
        name="mail-message-move",
    ),
    path(
        "messages/<uuid:message_id>/action/",
        MailMessageActionView.as_view(),
        name="mail-message-action",
    ),
    path(
        (
            "messages/<uuid:message_id>/attachments/"
            "<uuid:attachment_id>/download/"
        ),
        MailMessageAttachmentDownloadView.as_view(),
        name="mail-message-attachment-download",
    ),
    path(
        "drafts/",
        MailDraftsView.as_view(),
        name="mail-drafts",
    ),
    path(
        "messages/<uuid:message_id>/draft/",
        MailDraftDetailView.as_view(),
        name="mail-draft-detail",
    ),
    path(
        "messages/<uuid:message_id>/send/",
        MailDraftSendView.as_view(),
        name="mail-draft-send",
    ),
    path(
        "sync/",
        MailSyncView.as_view(),
        name="mail-sync",
    ),
]