from django.urls import path

from apps.storage.views import (
    FileShareDetailView,
    FileTagsView,
    StorageFileAccessView,
    StorageFileDetailView,
    StorageFileRestoreView,
    StorageFilesView,
    StorageFileSharesView,
    StorageFileTrashView,
    StorageFolderDetailView,
    StorageFoldersView,
    StorageReceivedSharesView,
    StorageShareRecipientSearchView,
    StorageSummaryView,
    StorageTagDetailView,
    StorageTagsView,
    StorageUploadView,
)


urlpatterns = [
    path(
        "summary/",
        StorageSummaryView.as_view(),
        name="storage-summary",
    ),
    path(
        "files/",
        StorageFilesView.as_view(),
        name="storage-files",
    ),
    path(
        "files/<uuid:file_id>/",
        StorageFileDetailView.as_view(),
        name="storage-file-detail",
    ),
    path(
        "files/<uuid:file_id>/access/",
        StorageFileAccessView.as_view(),
        name="storage-file-access",
    ),
    path(
        "files/<uuid:file_id>/trash/",
        StorageFileTrashView.as_view(),
        name="storage-file-trash",
    ),
    path(
        "files/<uuid:file_id>/restore/",
        StorageFileRestoreView.as_view(),
        name="storage-file-restore",
    ),
    path(
        "files/<uuid:file_id>/tags/",
        FileTagsView.as_view(),
        name="storage-file-tags",
    ),
    path(
        "files/<uuid:file_id>/shares/",
        StorageFileSharesView.as_view(),
        name="storage-file-shares",
    ),
    path(
        "uploads/",
        StorageUploadView.as_view(),
        name="storage-upload",
    ),
    path(
        "folders/",
        StorageFoldersView.as_view(),
        name="storage-folders",
    ),
    path(
        "folders/<uuid:folder_id>/",
        StorageFolderDetailView.as_view(),
        name="storage-folder-detail",
    ),
    path(
        "tags/",
        StorageTagsView.as_view(),
        name="storage-tags",
    ),
    path(
        "tags/<uuid:tag_id>/",
        StorageTagDetailView.as_view(),
        name="storage-tag-detail",
    ),
    path(
        "share-recipients/",
        StorageShareRecipientSearchView.as_view(),
        name="storage-share-recipient-search",
    ),
    path(
        "shares/received/",
        StorageReceivedSharesView.as_view(),
        name="storage-received-shares",
    ),
    path(
        "shares/<uuid:share_id>/",
        FileShareDetailView.as_view(),
        name="storage-share-detail",
    ),
    path(
        "shares/<uuid:share_id>/revoke/",
        FileShareDetailView.as_view(),
        name="storage-share-revoke",
    ),
    path(
        "shares/<uuid:share_id>/hide/",
        FileShareDetailView.as_view(),
        name="storage-share-hide",
    ),
]