from django.urls import path

from apps.notes.views import (
    NoteAttachmentAccessView,
    NoteAttachmentDetailView,
    NoteAttachmentsView,
    NoteAttachmentUploadView,
    NoteDetailView,
    NoteFolderDetailView,
    NoteFoldersView,
    NoteRestoreView,
    NotesView,
    NoteShareDetailView,
    NoteShareRecipientsView,
    NoteSharesView,
    NoteTagDetailView,
    NoteTagsAssignmentView,
    NoteTagsView,
    NoteTemplatesView,
    NoteTrashView,
    ReceivedNoteSharesView,
    SharedNoteDetailView,
)


urlpatterns = [
    path(
        "templates/",
        NoteTemplatesView.as_view(),
        name="note-templates",
    ),
    path(
        "",
        NotesView.as_view(),
        name="notes",
    ),
    path(
        "<uuid:note_id>/",
        NoteDetailView.as_view(),
        name="note-detail",
    ),
    path(
        "<uuid:note_id>/trash/",
        NoteTrashView.as_view(),
        name="note-trash",
    ),
    path(
        "<uuid:note_id>/restore/",
        NoteRestoreView.as_view(),
        name="note-restore",
    ),
    path(
        "<uuid:note_id>/tags/",
        NoteTagsAssignmentView.as_view(),
        name="note-tags-assignment",
    ),
    path(
        "<uuid:note_id>/attachments/",
        NoteAttachmentsView.as_view(),
        name="note-attachments",
    ),
    path(
        "<uuid:note_id>/attachments/upload/",
        NoteAttachmentUploadView.as_view(),
        name="note-attachments-upload",
    ),
    path(
        "<uuid:note_id>/attachments/<uuid:attachment_id>/",
        NoteAttachmentDetailView.as_view(),
        name="note-attachment-detail",
    ),
    path(
        "<uuid:note_id>/attachments/<uuid:attachment_id>/access/",
        NoteAttachmentAccessView.as_view(),
        name="note-attachment-access",
    ),
    path(
        "<uuid:note_id>/shares/",
        NoteSharesView.as_view(),
        name="note-shares",
    ),
    path(
        "share-recipients/",
        NoteShareRecipientsView.as_view(),
        name="note-share-recipient-search",
    ),
    path(
        "shares/received/",
        ReceivedNoteSharesView.as_view(),
        name="received-note-shares",
    ),
    path(
        "shared/<uuid:note_id>/",
        SharedNoteDetailView.as_view(),
        name="shared-note-detail",
    ),
    path(
        "shares/<uuid:share_id>/revoke/",
        NoteShareDetailView.as_view(),
        name="note-share-revoke",
    ),
    path(
        "shares/<uuid:share_id>/hide/",
        NoteShareDetailView.as_view(),
        name="note-share-hide",
    ),
    path(
        "folders/",
        NoteFoldersView.as_view(),
        name="note-folders",
    ),
    path(
        "folders/<uuid:folder_id>/",
        NoteFolderDetailView.as_view(),
        name="note-folder-detail",
    ),
    path(
        "tags/",
        NoteTagsView.as_view(),
        name="note-tags",
    ),
    path(
        "tags/<uuid:tag_id>/",
        NoteTagDetailView.as_view(),
        name="note-tag-detail",
    ),
]