from django.urls import path

from apps.statuses.views import (
    StatusAuthorStoriesView,
    StatusCollectionView,
    StatusDetailView,
    StatusFeedView,
    StatusFollowAcceptView,
    StatusFollowDetailView,
    StatusFollowDiscoverView,
    StatusFollowRejectView,
    StatusFollowersView,
    StatusFollowingView,
    StatusFollowRequestsView,
    StatusFollowsView,
    StatusMineView,
    StatusRepliesView,
    StatusTextBackgroundsView,
    StatusViewersView,
    StatusViewsView,
)


app_name = "statuses"

urlpatterns = [
    path(
        "text-backgrounds/",
        StatusTextBackgroundsView.as_view(),
        name="status-text-backgrounds",
    ),
    path(
        "feed/",
        StatusFeedView.as_view(),
        name="status-feed",
    ),
    path(
        "mine/",
        StatusMineView.as_view(),
        name="status-mine",
    ),
    path(
        "authors/<str:actor_type>/<uuid:actor_id>/",
        StatusAuthorStoriesView.as_view(),
        name="status-author-stories",
    ),
    path(
        "<uuid:status_id>/views/",
        StatusViewsView.as_view(),
        name="status-views",
    ),
    path(
        "<uuid:status_id>/viewers/",
        StatusViewersView.as_view(),
        name="status-viewers",
    ),
    path(
        "<uuid:status_id>/replies/",
        StatusRepliesView.as_view(),
        name="status-replies",
    ),
    path(
        "<uuid:status_id>/",
        StatusDetailView.as_view(),
        name="status-detail",
    ),
    path(
        "",
        StatusCollectionView.as_view(),
        name="status-collection",
    ),
    path(
        "follows/",
        StatusFollowsView.as_view(),
        name="status-follows",
    ),
    path(
        "follows/discover/",
        StatusFollowDiscoverView.as_view(),
        name="status-follow-discover",
    ),
    path(
        "follows/following/",
        StatusFollowingView.as_view(),
        name="status-following",
    ),
    path(
        "follows/followers/",
        StatusFollowersView.as_view(),
        name="status-followers",
    ),
    path(
        "follows/requests/",
        StatusFollowRequestsView.as_view(),
        name="status-follow-requests",
    ),
    path(
        "follows/<uuid:follow_id>/accept/",
        StatusFollowAcceptView.as_view(),
        name="status-follow-accept",
    ),
    path(
        "follows/<uuid:follow_id>/reject/",
        StatusFollowRejectView.as_view(),
        name="status-follow-reject",
    ),
    path(
        "follows/<uuid:follow_id>/",
        StatusFollowDetailView.as_view(),
        name="status-follow-detail",
    ),
]
