"""
Django settings for beeAppBack project.

Generated by 'django-admin startproject' using Django 6.1.
"""

import os
from pathlib import Path

from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def get_required_env(name: str) -> str:
    value = os.getenv(name)

    if not value:
        raise RuntimeError(
            f"Missing required environment variable: {name}"
        )

    return value


SECRET_KEY = get_required_env("SECRET_KEY")

DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "192.168.1.5",
    "practitioner-jenny-featured-wiki.trycloudflare.com",
]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "apps.accounts.apps.AccountsConfig",
    "apps.storage.apps.StorageConfig",
    "apps.notes.apps.NotesConfig",
    "apps.notifications.apps.NotificationsConfig",
    "apps.calendar.apps.CalendarConfig",
    "apps.integrations.apps.IntegrationsConfig",
    "apps.mail.apps.MailConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "beeAppBack.urls"

TEMPLATES = [
    {
        "BACKEND": (
            "django.template.backends.django.DjangoTemplates"
        ),
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "beeAppBack.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

STATIC_URL = "static/"

DATA_UPLOAD_MAX_MEMORY_SIZE = 52_428_800
FILE_UPLOAD_MAX_MEMORY_SIZE = 2_621_440
DATA_UPLOAD_MAX_NUMBER_FIELDS = 100

MAILERS = {
    "default": {
        "BACKEND": (
            "django.core.mail.backends.console.EmailBackend"
        ),
    },
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://192.168.1.5:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
    "http://192.168.1.5:3001",
    "http://localhost:8081",
    "http://127.0.0.1:8081",
    "http://192.168.1.5:8081",
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://192.168.1.5:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
    "http://192.168.1.5:3001",
]

GOOGLE_OAUTH_CLIENT_ID = get_required_env(
    "GOOGLE_OAUTH_CLIENT_ID"
)

GOOGLE_OAUTH_CLIENT_SECRET = get_required_env(
    "GOOGLE_OAUTH_CLIENT_SECRET"
)

GOOGLE_OAUTH_REDIRECT_URI = get_required_env(
    "GOOGLE_OAUTH_REDIRECT_URI"
)

MICROSOFT_OAUTH_CLIENT_ID = get_required_env(
    "MICROSOFT_OAUTH_CLIENT_ID"
)

MICROSOFT_OAUTH_CLIENT_SECRET = get_required_env(
    "MICROSOFT_OAUTH_CLIENT_SECRET"
)

MICROSOFT_OAUTH_REDIRECT_URI = get_required_env(
    "MICROSOFT_OAUTH_REDIRECT_URI"
)

INTEGRATION_TOKEN_ENCRYPTION_KEY = get_required_env(
    "INTEGRATION_TOKEN_ENCRYPTION_KEY"
)

INTEGRATION_MOBILE_SUCCESS_REDIRECT = get_required_env(
    "INTEGRATION_MOBILE_SUCCESS_REDIRECT"
)

INTEGRATION_MOBILE_FAILURE_REDIRECT = get_required_env(
    "INTEGRATION_MOBILE_FAILURE_REDIRECT"
)

INTEGRATION_WEB_RESULT_REDIRECT = get_required_env(
    "INTEGRATION_WEB_RESULT_REDIRECT"
)