"""
Django settings for beeAppBack project.

Generated by 'django-admin startproject' using Django 6.1.
"""

import os
from pathlib import Path

from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def get_required_env(name: str) -> str:
    value = os.getenv(name)

    if not value:
        raise RuntimeError(
            f"Missing required environment variable: {name}"
        )

    return value


SECRET_KEY = get_required_env("SECRET_KEY")

DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [
    "beeappai-production.up.railway.app",
    "localhost",
    "127.0.0.1",
    "192.168.1.5",
]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "apps.chat",
    "apps.calls.apps.CallsConfig",
    "corsheaders",
    "apps.accounts.apps.AccountsConfig",
    "apps.storage.apps.StorageConfig",
    "apps.notes.apps.NotesConfig",
    "apps.notifications.apps.NotificationsConfig",
    "apps.calendar.apps.CalendarConfig",
    "apps.integrations.apps.IntegrationsConfig",
    "apps.mail.apps.MailConfig",
    "apps.commercial.apps.CommercialConfig",
    "apps.statuses",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "beeAppBack.urls"

TEMPLATES = [
    {
        "BACKEND": (
            "django.template.backends.django.DjangoTemplates"
        ),
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "beeAppBack.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

STATIC_URL = "static/"

# El límite HTTP deja margen para multipart/form-data.
# Los servicios de Estados siguen validando un máximo real de 50 MB
# por archivo de video y 10 MB para imagen/GIF.
DATA_UPLOAD_MAX_MEMORY_SIZE = 62_914_560
FILE_UPLOAD_MAX_MEMORY_SIZE = 2_621_440
DATA_UPLOAD_MAX_NUMBER_FIELDS = 100

MAILERS = {
    "default": {
        "BACKEND": (
            "django.core.mail.backends.console.EmailBackend"
        ),
    },
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://192.168.1.5:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
    "http://192.168.1.5:3001",
    "http://localhost:8081",
    "http://127.0.0.1:8081",
    "http://192.168.1.5:8081",
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://192.168.1.5:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
    "http://192.168.1.5:3001",
]

GOOGLE_OAUTH_CLIENT_ID = get_required_env(
    "GOOGLE_OAUTH_CLIENT_ID"
)

GOOGLE_OAUTH_CLIENT_SECRET = get_required_env(
    "GOOGLE_OAUTH_CLIENT_SECRET"
)

GOOGLE_OAUTH_REDIRECT_URI = get_required_env(
    "GOOGLE_OAUTH_REDIRECT_URI"
)

MICROSOFT_OAUTH_CLIENT_ID = get_required_env(
    "MICROSOFT_OAUTH_CLIENT_ID"
)

MICROSOFT_OAUTH_CLIENT_SECRET = get_required_env(
    "MICROSOFT_OAUTH_CLIENT_SECRET"
)

MICROSOFT_OAUTH_REDIRECT_URI = get_required_env(
    "MICROSOFT_OAUTH_REDIRECT_URI"
)

INTEGRATION_TOKEN_ENCRYPTION_KEY = get_required_env(
    "INTEGRATION_TOKEN_ENCRYPTION_KEY"
)

INTEGRATION_MOBILE_SUCCESS_REDIRECT = get_required_env(
    "INTEGRATION_MOBILE_SUCCESS_REDIRECT"
)

INTEGRATION_MOBILE_FAILURE_REDIRECT = get_required_env(
    "INTEGRATION_MOBILE_FAILURE_REDIRECT"
)

INTEGRATION_WEB_RESULT_REDIRECT = get_required_env(
    "INTEGRATION_WEB_RESULT_REDIRECT"
)

# Chat shared cache configuration.
#
# Production: define REDIS_URL so all Django workers and instances share
# the same Redis cache. Local development without REDIS_URL uses a
# process-local fallback only; it must not be used as production cache.
REDIS_URL = os.getenv("REDIS_URL")

if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": (
                    "django_redis.client.DefaultClient"
                ),
                "CONNECTION_POOL_KWARGS": {
                    "max_connections": 100,
                    "retry_on_timeout": True,
                },
            },
            "KEY_PREFIX": "beeapp",
            "TIMEOUT": 60,
        },
    }
else:
    CACHES = {
        "default": {
            "BACKEND": (
                "django.core.cache.backends.locmem.LocMemCache"
            ),
            "LOCATION": "beeapp-local-cache",
            "TIMEOUT": 60,
        },
    }

# End Chat shared cache configuration.

REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_RATES": {
        "chat_user": "120/min",
        "chat_message_send": "30/min",
        "chat_attachment_upload": "10/min",
        "chat_reaction": "60/min",
        "chat_group_mutation": "20/min",
        "chat_recipient_search": "30/min",
        "chat_sync": "30/min",
        "status_user": "120/min",
        "status_publish": "12/min",
        "status_media_publish": "8/min",
        "status_view": "120/min",
        "status_reply": "30/min",
        "call_user": "120/min",
        "call_start": "12/min",
        "call_join": "30/min",
        "call_mutation": "60/min",
    },
}
AGORA_APP_ID = get_required_env("AGORA_APP_ID")

AGORA_APP_CERTIFICATE = get_required_env(
    "AGORA_APP_CERTIFICATE"
)

AGORA_RTC_TOKEN_TTL_SECONDS = int(
    os.getenv("AGORA_RTC_TOKEN_TTL_SECONDS", "3600")
)
