from django.urls import path

from apps.accounts.views import (
    CurrentProfileView,
    DeviceSessionDetailView,
    DeviceSessionListView,
    LoginUserView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    PasswordResetVerifyView,
    PhoneOtpMobileVerifyView,
    PhoneOtpRequestView,
    PhoneOtpVerifyView,
    QrLoginChallengeDetailView,
    QrLoginChallengeView,
    QrLoginScanView,
    RegisterUserView,
    RevokeAllDeviceSessionsView,
    SessionRefreshView,
    UpdateAssistantSettingsView,
    UpdateOnboardingProfileView,
    WebSessionActivateView,
    WebSessionLogoutView,
    WebSessionProfileView,
)


urlpatterns = [
    path(
        "register/",
        RegisterUserView.as_view(),
        name="register-user",
    ),
    path(
        "login/",
        LoginUserView.as_view(),
        name="login-user",
    ),
    path(
        "session/refresh/",
        SessionRefreshView.as_view(),
        name="refresh-session",
    ),
    path(
        "login/phone/request-otp/",
        PhoneOtpRequestView.as_view(),
        name="request-phone-otp",
    ),
    path(
        "login/phone/verify-otp/",
        PhoneOtpVerifyView.as_view(),
        name="verify-phone-otp",
    ),
    path(
        "login/phone/verify-otp/mobile/",
        PhoneOtpMobileVerifyView.as_view(),
        name="verify-phone-otp-mobile",
    ),
    path(
        "password-reset/request/",
        PasswordResetRequestView.as_view(),
        name="password-reset-request",
    ),
    path(
        "password-reset/verify/",
        PasswordResetVerifyView.as_view(),
        name="password-reset-verify",
    ),
    path(
        "password-reset/confirm/",
        PasswordResetConfirmView.as_view(),
        name="password-reset-confirm",
    ),
    path(
        "me/",
        CurrentProfileView.as_view(),
        name="current-profile",
    ),
    path(
        "me/profile/",
        UpdateOnboardingProfileView.as_view(),
        name="update-onboarding-profile",
    ),
    path(
        "me/assistant/",
        UpdateAssistantSettingsView.as_view(),
        name="update-assistant-settings",
    ),
    path(
        "me/devices/",
        DeviceSessionListView.as_view(),
        name="device-sessions",
    ),
    path(
        "me/devices/others/",
        RevokeAllDeviceSessionsView.as_view(),
        name="revoke-all-device-sessions",
    ),
    path(
        "me/devices/<uuid:device_id>/",
        DeviceSessionDetailView.as_view(),
        name="device-session-detail",
    ),
    path(
        "qr-login/challenges/",
        QrLoginChallengeView.as_view(),
        name="qr-login-challenge",
    ),
    path(
        "qr-login/challenges/<str:challenge_token>/",
        QrLoginChallengeDetailView.as_view(),
        name="qr-login-challenge-detail",
    ),
    path(
        "qr-login/scan/",
        QrLoginScanView.as_view(),
        name="qr-login-scan",
    ),
    path(
        "web-session/activate/",
        WebSessionActivateView.as_view(),
        name="web-session-activate",
    ),
    path(
        "web-session/me/",
        WebSessionProfileView.as_view(),
        name="web-session-profile",
    ),
    path(
        "web-session/logout/",
        WebSessionLogoutView.as_view(),
        name="web-session-logout",
    ),
]