from django.urls import path

from apps.calendar.views import (
    CalendarBootstrapView,
    CalendarConflictView,
    CalendarDetailView,
    CalendarEventAttendeesView,
    CalendarEventDetailView,
    CalendarEventDuplicateView,
    CalendarEventInviteeRequestsView,
    CalendarEventRsvpView,
    CalendarEventsView,
    CalendarExternalCalendarDetailView,
    CalendarIntegrationDetailView,
    CalendarIntegrationDiscoverCalendarsView,
    CalendarIntegrationExternalCalendarsView,
    CalendarIntegrationSyncView,
    CalendarIntegrationsView,
    CalendarInviteeRequestDetailView,
    CalendarPreferencesView,
    CalendarShareAcceptView,
    CalendarShareDetailView,
    CalendarSharesView,
    CalendarTagDetailView,
    CalendarTagsView,
    CalendarUsersSearchView,
    CalendarsView,
    DeclinedEventVisibilityView,
)


urlpatterns = [
    path(
        "bootstrap/",
        CalendarBootstrapView.as_view(),
        name="calendar-bootstrap",
    ),
    path(
        "users/search/",
        CalendarUsersSearchView.as_view(),
        name="calendar-users-search",
    ),
    path(
        "conflicts/",
        CalendarConflictView.as_view(),
        name="calendar-conflicts",
    ),
    path(
        "preferences/",
        CalendarPreferencesView.as_view(),
        name="calendar-preferences",
    ),
    path(
        "integrations/",
        CalendarIntegrationsView.as_view(),
        name="calendar-integrations",
    ),
    path(
        "integrations/<uuid:integration_id>/",
        CalendarIntegrationDetailView.as_view(),
        name="calendar-integration-detail",
    ),
    path(
        (
            "integrations/<uuid:integration_id>/"
            "external-calendars/"
        ),
        CalendarIntegrationExternalCalendarsView.as_view(),
        name="calendar-integration-external-calendars",
    ),
    path(
        (
            "integrations/<uuid:integration_id>/"
            "discover-calendars/"
        ),
        CalendarIntegrationDiscoverCalendarsView.as_view(),
        name="calendar-integration-discover-calendars",
    ),
    path(
        (
            "integrations/<uuid:integration_id>/"
            "sync/"
        ),
        CalendarIntegrationSyncView.as_view(),
        name="calendar-integration-sync",
    ),
    path(
        "external-calendars/<uuid:external_calendar_id>/",
        CalendarExternalCalendarDetailView.as_view(),
        name="calendar-external-calendar-detail",
    ),
    path(
        "calendars/",
        CalendarsView.as_view(),
        name="calendars",
    ),
    path(
        "calendars/<uuid:calendar_id>/",
        CalendarDetailView.as_view(),
        name="calendar-detail",
    ),
    path(
        "calendars/<uuid:calendar_id>/shares/",
        CalendarSharesView.as_view(),
        name="calendar-shares",
    ),
    path(
        "calendar-shares/<uuid:share_id>/accept/",
        CalendarShareAcceptView.as_view(),
        name="calendar-share-accept",
    ),
    path(
        "calendar-shares/<uuid:share_id>/revoke/",
        CalendarShareDetailView.as_view(),
        name="calendar-share-revoke",
    ),
    path(
        "tags/",
        CalendarTagsView.as_view(),
        name="calendar-tags",
    ),
    path(
        "tags/<uuid:tag_id>/",
        CalendarTagDetailView.as_view(),
        name="calendar-tag-detail",
    ),
    path(
        "events/",
        CalendarEventsView.as_view(),
        name="calendar-events",
    ),
    path(
        "events/<uuid:event_id>/",
        CalendarEventDetailView.as_view(),
        name="calendar-event-detail",
    ),
    path(
        "events/<uuid:event_id>/duplicate/",
        CalendarEventDuplicateView.as_view(),
        name="calendar-event-duplicate",
    ),
    path(
        "events/<uuid:event_id>/attendees/",
        CalendarEventAttendeesView.as_view(),
        name="calendar-event-attendees",
    ),
    path(
        "events/<uuid:event_id>/rsvp/",
        CalendarEventRsvpView.as_view(),
        name="calendar-event-rsvp",
    ),
    path(
        "events/<uuid:event_id>/declined-visibility/",
        DeclinedEventVisibilityView.as_view(),
        name="calendar-declined-event-visibility",
    ),
    path(
        "events/<uuid:event_id>/invitee-requests/",
        CalendarEventInviteeRequestsView.as_view(),
        name="calendar-event-invitee-requests",
    ),
    path(
        "invitee-requests/<uuid:request_id>/review/",
        CalendarInviteeRequestDetailView.as_view(),
        name="calendar-invitee-request-review",
    ),
]